services:
  - type: web
    name: shmirot
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: shmirot-db
    databaseName: shmirot
    user: shmirot_user 